"""Generates most of the bundled 'photo' dashboard backgrounds shipped
with the app (assets/backgrounds/*.jpg -- dashboard_theme.py's
BUNDLED_BACKGROUND_IMAGES). A one-off authoring tool, not run by the
app itself: the output JPEGs are what actually gets committed, and
loaded at runtime via dashboard_theme._build_background_image()
resolving them through paths.resource_path("backgrounds", ...). Only
re-run this (from the repo root: `python scripts/generate_backgrounds.
py`) to redesign one of these looks; nothing else in the app calls it.
(The exception is circuit_bloom.jpg, which isn't generated by this
script at all -- it's a real user's own uploaded photo, center-cropped
and resized to match; see CHANGELOG.md/ROADMAP.md for that one.)

Each is rendered at 1920x960 (matches the panel's 2:1 aspect so
ImageOps.fit's cover-crop never has to cut much off either axis) with
layered blur/noise/radial-gradient techniques -- no external image
model involved, everything here is plain PIL/numpy math -- aiming for
something that reads as an actual generated picture rather than this
theme's existing flat-gradient/line-art background modes (grid/
starfield/radial/solid).
"""
import math
import os
import random

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

W, H = 1920, 960
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets", "backgrounds")


def rounded_rect(draw, box, radius, **kwargs):
    """A local copy of dashboard_theme.py's own tiny helper of the same
    name (not imported from there -- this script intentionally has no
    dependency on the app package, just PIL/numpy) -- falls back to a
    plain rectangle on a very old Pillow with no rounded_rectangle."""
    try:
        draw.rounded_rectangle(box, radius=radius, **kwargs)
    except AttributeError:  # noqa: BLE001
        draw.rectangle(box, **kwargs)


def save(img, name):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, name)
    img.convert("RGB").save(path, quality=90)
    print("wrote", path, img.size)


def vertical_gradient(w, h, top, bottom):
    top = np.array(top, dtype=np.float32)
    bottom = np.array(bottom, dtype=np.float32)
    t = np.linspace(0, 1, h, dtype=np.float32).reshape(h, 1, 1)
    row = top * (1 - t) + bottom * t
    arr = np.repeat(row, w, axis=1)
    return Image.fromarray(arr.astype(np.uint8), "RGB")


def add_stars(img, count, rng, max_r=1.6, colors=((255, 255, 255),)):
    draw = ImageDraw.Draw(img, "RGBA")
    w, h = img.size
    for _ in range(count):
        x, y = rng.uniform(0, w), rng.uniform(0, h)
        r = rng.uniform(0.3, max_r)
        a = rng.randint(80, 230)
        c = rng.choice(colors)
        draw.ellipse([x - r, y - r, x + r, y + r], fill=(*c, a))
    return img


def soft_blob(w, h, cx, cy, radius, color, strength=255):
    """One RGBA layer: a radial-falloff blob of `color`, soft-edged via
    a squared falloff (softer than linear, avoids a visible hard ring
    at the blur radius) -- the basic unit every nebula/bokeh/aurora
    background below composites many of, at different positions/sizes/
    colors, to build up something that doesn't look like a single flat
    gradient."""
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    ys, xs = np.mgrid[0:h, 0:w]
    d = np.sqrt((xs - cx) ** 2 + (ys - cy) ** 2) / radius
    falloff = np.clip(1.0 - d, 0, 1) ** 2
    alpha = (falloff * strength).astype(np.uint8)
    rgb = np.zeros((h, w, 3), dtype=np.uint8)
    rgb[:, :] = color
    arr = np.dstack([rgb, alpha])
    return Image.fromarray(arr, "RGBA")


# All four below build up their look by compositing several `soft_blob`/
# band RGBA layers with Image.alpha_composite -- deliberately NOT
# ImageChops.screen, which was tried first: it screens the alpha
# channel too, as if it were just another color channel, which
# corrupts each layer's opacity instead of combining it properly and
# rendered as a washed-out gray fog instead of visible color.

# ---------------------------------------------------------------------
# 1. Aurora Glow -- deep night sky, a starfield, and 4 soft flowing
# aurora ribbons (sine-perturbed horizontal bands, blurred heavily so
# they read as glowing curtains of light rather than stripes).
# ---------------------------------------------------------------------
def make_aurora(seed=1):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (6, 10, 22), (2, 3, 8))
    img = add_stars(img, 260, rng, max_r=1.3)

    ribbon_colors = [(60, 230, 170), (70, 200, 255), (150, 110, 255), (60, 255, 210)]
    aurora_layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for i, base_color in enumerate(ribbon_colors):
        band = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        draw = ImageDraw.Draw(band)
        base_y = H * (0.18 + i * 0.11) + rng.uniform(-20, 20)
        amp = rng.uniform(50, 110)
        freq = rng.uniform(1.4, 2.4)
        phase = rng.uniform(0, math.tau)
        thickness = rng.uniform(70, 140)
        for x in range(0, W, 4):
            y = base_y + amp * math.sin(x / W * math.tau * freq + phase)
            a = int(46 + 18 * math.sin(x / W * math.tau * 0.7 + i))
            draw.line([(x, y - thickness / 2), (x, y + thickness / 2)],
                      fill=(*base_color, max(10, a)), width=4)
        band = band.filter(ImageFilter.GaussianBlur(34))
        aurora_layer = Image.alpha_composite(aurora_layer, band)
    img = Image.alpha_composite(img.convert("RGBA"), aurora_layer).convert("RGB")

    # A faint horizon glow at the bottom so it doesn't just stop dead.
    glow = soft_blob(W, H, W * 0.5, H * 1.05, H * 0.9, (40, 60, 90), strength=90)
    img = Image.alpha_composite(img.convert("RGBA"), glow).convert("RGB")
    return img


# ---------------------------------------------------------------------
# 2. Deep Nebula -- several large soft color blobs over black, plus a
# dense star field and a few brighter "core" points.
# ---------------------------------------------------------------------
def make_nebula(seed=2):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (10, 4, 16), (3, 2, 8)).convert("RGBA")

    palette = [(180, 60, 200), (70, 90, 230), (230, 70, 140), (90, 200, 220), (140, 60, 220)]
    cloud = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for _ in range(9):
        color = rng.choice(palette)
        cx = rng.uniform(W * 0.1, W * 0.9)
        cy = rng.uniform(H * 0.1, H * 0.9)
        radius = rng.uniform(H * 0.35, H * 0.75)
        blob = soft_blob(W, H, cx, cy, radius, color, strength=rng.randint(110, 200))
        cloud = Image.alpha_composite(cloud, blob)
    cloud = cloud.filter(ImageFilter.GaussianBlur(22))
    img = Image.alpha_composite(img, cloud)

    img = img.convert("RGB")
    img = add_stars(img, 380, rng, max_r=1.4)
    # A few brighter "core" stars for sparkle.
    add_stars(img, 18, rng, max_r=2.6, colors=((255, 255, 255), (255, 240, 210)))
    return img


# ---------------------------------------------------------------------
# 3. Synthwave Sunset -- retro outrun look: purple-to-orange sky, a
# glowing sun low on the horizon, a perspective grid "floor".
# ---------------------------------------------------------------------
def make_synthwave(seed=3):
    sky_top, sky_bottom = (40, 10, 70), (255, 130, 60)
    img = vertical_gradient(W, H, sky_top, sky_bottom).convert("RGBA")

    horizon = int(H * 0.62)
    sun_cx, sun_cy, sun_r = W * 0.5, horizon - H * 0.02, H * 0.30

    disc = vertical_gradient(int(sun_r * 2), int(sun_r * 2), (255, 235, 150), (255, 60, 110)).convert("RGBA")
    mask = Image.new("L", disc.size, 0)
    ImageDraw.Draw(mask).ellipse([0, 0, disc.size[0] - 1, disc.size[1] - 1], fill=255)
    mdraw = ImageDraw.Draw(mask)
    # Cut a few horizontal gaps into the lower third of the disc for
    # the classic retro "scanline sun" look.
    gap_h = max(2, int(sun_r * 0.05))
    y = int(sun_r * 1.05)
    step = int(sun_r * 0.16)
    while y < sun_r * 2:
        mdraw.rectangle([0, y, disc.size[0], y + gap_h], fill=0)
        y += step
    sun_layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sun_layer.paste(disc, (int(sun_cx - sun_r), int(sun_cy - sun_r)), mask)

    # Sun glow behind/around it, then the sun itself on top.
    glow = soft_blob(W, H, sun_cx, sun_cy, sun_r * 2.1, (255, 150, 120), strength=70)
    img = Image.alpha_composite(img, glow)
    img = Image.alpha_composite(img, sun_layer)

    # Ground: dark plane below the horizon with a receding grid.
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, horizon, W, H], fill=(12, 4, 22, 255))
    vp = (W * 0.5, horizon - H * 0.04)
    n_lines = 14
    for i in range(-n_lines, n_lines + 1):
        x0 = W * 0.5 + i * (W * 0.9 / n_lines)
        draw.line([vp, (x0, H)], fill=(255, 90, 180, 130), width=2)
    n_h = 9
    for j in range(1, n_h + 1):
        t = (j / n_h) ** 1.6
        y = horizon + t * (H - horizon)
        alpha = int(160 * (1 - t) + 40)
        draw.line([(0, y), (W, y)], fill=(255, 90, 180, alpha), width=2)

    # A light haze band right at the horizon softens the sun/grid seam.
    haze = soft_blob(W, H, sun_cx, horizon, H * 0.5, (255, 180, 140), strength=60)
    img = Image.alpha_composite(img, haze)
    return img.convert("RGB")


# ---------------------------------------------------------------------
# 4. Bokeh Night -- dark gradient with soft, variously-sized glowing
# blurred circles scattered across it, like an out-of-focus city-lights
# photo.
# ---------------------------------------------------------------------
def make_bokeh(seed=4):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (8, 12, 22), (3, 4, 9)).convert("RGBA")

    palette = [(255, 200, 120), (120, 200, 255), (255, 120, 170), (150, 255, 210), (255, 255, 255)]
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    for _ in range(46):
        color = rng.choice(palette)
        cx = rng.uniform(0, W)
        cy = rng.uniform(0, H)
        radius = rng.uniform(18, 90)
        strength = rng.randint(60, 170)
        blob = soft_blob(W, H, cx, cy, radius, color, strength=strength)
        layer = Image.alpha_composite(layer, blob)
    layer = layer.filter(ImageFilter.GaussianBlur(6))
    img = Image.alpha_composite(img, layer)
    return img.convert("RGB")


# ---------------------------------------------------------------------
# 5/6. Cherry Blossom / Petal Dream -- v2, redesigned after direct
# feedback that v1 ("a scatter of blurred flower blobs behind text")
# read as a generic photo background with text floating on top, not as
# one integrated design -- unlike the reference photo, where the
# ornate corner swirls, the banner behind the title, and the flowers
# all visibly belong to the same card the text sits in.
#
# What changed, concretely: real line art (nested arcs forming a
# corner swirl, `_draw_corner_flourish()`) instead of only soft blobs;
# a scroll/banner shape drawn directly behind where the title text
# lands (`_draw_title_banner()`); thin rule lines marking the column
# header underlines and the vertical divider between the two stat
# columns (`_draw_rule()`); and, most importantly, every one of these
# is positioned using the *exact same x/y fractions* as the matching
# preset's own elements (dashboard_theme.py's "Cherry Blossom"/"Petal
# Dream" entries -- see _CHERRY_LAYOUT/_PETAL_LAYOUT below, which
# mirror those elements' x/y verbatim) instead of being scattered at
# random. The flower motifs are cut down and deliberately placed too:
# a single "bouquet" medallion anchoring the empty middle gap between
# the two columns (standing in for the reference's portrait as the
# composition's visual anchor) plus a light scatter confined to the
# margins, not layered across the text zones the way v1's 60-petal
# "falling blossom" drift was -- so the columns stay calm and legible
# instead of competing with the stat rows for attention.
#
# NOTE: because of that coordinate mirroring, a future edit to either
# preset's own element x/y in dashboard_theme.py should update the
# matching _CHERRY_LAYOUT/_PETAL_LAYOUT constants here too (and
# re-run this script) to keep the background's frame/divider/banner
# aligned with where the text actually lands.
# ---------------------------------------------------------------------
_CHERRY_LAYOUT = {
    "title_y": 0.075, "header_y": 0.235, "col_l": 0.22, "col_r": 0.78,
    "row_top": 0.35, "row_bottom": 0.71, "clock_y": 0.885,
}
_PETAL_LAYOUT = {
    "title_y": 0.075, "header_y": 0.22, "col_l": 0.22, "col_r": 0.78,
    "row_top": 0.335, "row_bottom": 0.68, "clock_y": 0.9,
}


def _draw_petal_flower(layer, cx, cy, size, petal_color, center_color, rng, petals=5):
    """One flower doodle: `petals` soft-edged ellipse "petals" arranged
    in a ring around (cx, cy) via soft_blob (so they blend into the
    layer instead of showing hard ellipse edges), plus a small brighter
    center. Returns nothing -- composites straight onto `layer`."""
    w, h = layer.size
    petal_r = size * 0.62
    orbit = size * 0.55
    base_angle = rng.uniform(0, math.tau)
    for i in range(petals):
        angle = base_angle + i * (math.tau / petals)
        px = cx + math.cos(angle) * orbit
        py = cy + math.sin(angle) * orbit
        blob = soft_blob(w, h, px, py, petal_r, petal_color, strength=rng.randint(130, 190))
        # Image.alpha_composite (the instance method, not the module
        # function used elsewhere in this file) composites in place.
        layer.alpha_composite(blob)
    center = soft_blob(w, h, cx, cy, size * 0.32, center_color, strength=210)
    layer.alpha_composite(center)


def _draw_leaf(layer, cx, cy, length, width_, angle_deg, color, alpha=170):
    """A small rotated-ellipse leaf, for filling out a flower medallion
    into something that reads as an arranged bouquet rather than just
    flower heads. Drawn on its own tiny canvas and rotated (PIL has no
    rotated-ellipse primitive), then composited onto `layer` at (cx,
    cy) via the instance `alpha_composite(im, dest)` form -- cheaper
    than allocating a full canvas-sized RGBA layer per leaf the way
    soft_blob()-based shapes do, since a leaf doesn't need the same
    soft radial falloff."""
    pad = 2
    leaf = Image.new("RGBA", (length + pad * 2, width_ + pad * 2), (0, 0, 0, 0))
    ImageDraw.Draw(leaf).ellipse([pad, pad, pad + length, pad + width_], fill=(*color, alpha))
    leaf = leaf.rotate(angle_deg, expand=True, resample=Image.BICUBIC)
    lw, lh = leaf.size
    layer.alpha_composite(leaf, (int(cx - lw / 2), int(cy - lh / 2)))


def _draw_flower_medallion(layer, cx, cy, size, petal_palette, center_color, leaf_color, rng):
    """A small arranged bouquet -- 3 flowers (one larger center, two
    smaller flanking it lower down) plus a handful of leaves filling
    the gaps between and below them -- used once per background as the
    composition's visual anchor, in the empty gap between the two stat
    columns. Deliberately just `_draw_petal_flower()` called a few
    times with real relative sizing/placement instead of a denser
    flower or a bigger single one, so it reads as an arrangement (like
    the reference's framed portrait anchoring its own layout) rather
    than one more scattered blob."""
    # 3 short leaves tucked close under the flower cluster, mostly
    # meant to peek out from beneath it rather than spread wide --
    # v1's leaves were both longer than the flowers and angled out
    # past their edges, reading as stray antennae instead of a
    # supporting stem/foliage. Drawn *before* the flowers so the
    # petals sit on top and only each leaf's lower tip shows.
    _draw_leaf(layer, cx - size * 0.32, cy + size * 0.62, int(size * 0.62), int(size * 0.2),
               25, leaf_color, alpha=170)
    _draw_leaf(layer, cx + size * 0.32, cy + size * 0.62, int(size * 0.62), int(size * 0.2),
               -25, leaf_color, alpha=170)
    _draw_leaf(layer, cx, cy + size * 0.7, int(size * 0.55), int(size * 0.18), 90, leaf_color, alpha=170)
    # 2 smaller flowers flanking a larger center one, all close enough
    # together to read as one bouquet rather than 3 separate blooms --
    # drawn largest-last so the center flower sits visually on top.
    _draw_petal_flower(layer, cx - size * 0.6, cy + size * 0.22, size * 0.58,
                        rng.choice(petal_palette), center_color, rng)
    _draw_petal_flower(layer, cx + size * 0.6, cy + size * 0.22, size * 0.58,
                        rng.choice(petal_palette), center_color, rng)
    _draw_petal_flower(layer, cx, cy, size * 1.05, rng.choice(petal_palette), center_color, rng, petals=6)


def _draw_corner_flourish(size, color, rng):
    """An ornamental swirl -- 3 nested quarter-circle arcs curling in
    from a corner, plus 3 small embellishment dots along the outermost
    one -- rendered as real line art (draw.arc), not a soft blob, so it
    reads as an intentional frame the way the reference photo's gold
    corner scrollwork does. Returns an RGBA image of size (size, size)
    drawn assuming it anchors the *top-left* corner (its own (0, 0));
    callers flip it via Image.transpose() for the other 3 corners
    before compositing (see the two make_*() functions below)."""
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    radii = (size * 0.92, size * 0.62, size * 0.36)
    widths = (max(2, int(size * 0.02)), max(2, int(size * 0.015)), max(2, int(size * 0.011)))
    for r, w in zip(radii, widths):
        draw.arc([0 - r, 0 - r, r, r], start=0, end=90, fill=(*color, 235), width=w)
    for t in (0.18, 0.5, 0.82):
        ang = math.radians(90 * t)
        r = radii[0] * 0.8
        px, py = r * math.cos(ang), r * math.sin(ang)
        dr = max(2, int(size * 0.022))
        draw.ellipse([px - dr, py - dr, px + dr, py + dr], fill=(*color, 220))
    return img


def _place_corner_flourishes(layer, size, color, margin, rng):
    """Composites `_draw_corner_flourish()` into all 4 corners of
    `layer` (an RGBA image), flipped as needed so each one visibly
    curls inward from its own actual corner."""
    w, h = layer.size
    base = _draw_corner_flourish(size, color, rng)
    layer.alpha_composite(base, (margin, margin))
    layer.alpha_composite(base.transpose(Image.FLIP_LEFT_RIGHT), (w - margin - size, margin))
    layer.alpha_composite(base.transpose(Image.FLIP_TOP_BOTTOM), (margin, h - margin - size))
    layer.alpha_composite(base.transpose(Image.ROTATE_180), (w - margin - size, h - margin - size))


def _draw_title_banner(draw, cx, cy, width, height, color, line_width=3):
    """A ribbon/pennant outline behind the title text: a flat-sided
    rectangular body with a V-notch cut into each end, the classic
    "banner" silhouette -- one continuous closed polygon (traced as a
    connected line loop, since not every Pillow version supports
    polygon(outline=..., width=...)), so the two ends read as attached
    swallow-tails instead of v1's disconnected rounded-pill-plus-
    floating-chevrons. Outline only, so the title text stays fully
    legible sitting on top of it."""
    left, right = cx - width / 2, cx + width / 2
    top, bottom = cy - height / 2, cy + height / 2
    tail = height * 0.55
    points = [
        (left - tail, top), (left, cy), (left - tail, bottom),
        (left, bottom), (right, bottom),
        (right + tail, bottom), (right, cy), (right + tail, top),
        (right, top), (left, top),
    ]
    for i in range(len(points)):
        p0, p1 = points[i], points[(i + 1) % len(points)]
        draw.line([p0, p1], fill=(*color, 235), width=line_width)


def _draw_rule(draw, x0, y, x1, color, width=2):
    draw.line([(x0, y), (x1, y)], fill=(*color, 190), width=width)


def _card_frame_and_divider(img, layout, accent_color, medallion_cy=None, medallion_gap=0):
    """The parts of the "integrated card" look that are straight line
    art rather than flowers: a thin rule under each column header
    (CPU/GPU, or System/Graphics), and a vertical divider between the
    two columns that stops short of the header row and the clock row
    so it reads as separating the *stat block* specifically, not the
    whole card top-to-bottom. Shared by both make_*() functions below
    since both presets use the same 2-column layout shape.

    `medallion_cy`/`medallion_gap` (both in pixels, optional): when the
    bouquet medallion sits on this same vertical line, the divider is
    drawn as two shorter segments stopping `medallion_gap` above/below
    it instead of one continuous line straight through the flowers --
    v1 drew it as a single line, which looked like a skewer stabbed
    through the bouquet in testing."""
    draw = ImageDraw.Draw(img)
    header_y = layout["header_y"] * H
    row_top = layout["row_top"] * H
    row_bottom = layout["row_bottom"] * H
    col_l, col_r = layout["col_l"] * W, layout["col_r"] * W
    rule_half = W * 0.055
    _draw_rule(draw, col_l - rule_half, header_y + H * 0.028, col_l + rule_half, accent_color)
    _draw_rule(draw, col_r - rule_half, header_y + H * 0.028, col_r + rule_half, accent_color)
    divider_top = header_y + H * 0.06
    divider_bottom = row_bottom + H * 0.05
    if medallion_cy is not None:
        draw.line([(W * 0.5, divider_top), (W * 0.5, medallion_cy - medallion_gap)],
                  fill=(*accent_color, 130), width=2)
        draw.line([(W * 0.5, medallion_cy + medallion_gap), (W * 0.5, divider_bottom)],
                  fill=(*accent_color, 130), width=2)
    else:
        draw.line([(W * 0.5, divider_top), (W * 0.5, divider_bottom)], fill=(*accent_color, 130), width=2)


_BLOOM = {
    "left": (0.030, 0.155, 0.485, 0.930),
    "right": (0.515, 0.155, 0.970, 0.930),
}


def _bloom_chassis(img, gold, card_fill, card_border, petal_palette, center_color,
                   leaf_color, rng, corner=0.30):
    """The shared structure of the two floral themes, v3: corner
    scrollwork, two translucent stat cards, a bouquet tucked into each
    of the two opposite outer corners, and a light blossom scatter
    confined to the margins.

    v2 built these around a title banner and a centered bouquet between
    two bare text columns. Both are gone: the titles were removed from
    every preset (a theme shouldn't spend its best real estate writing
    its own name), which left the banner framing nothing, and the
    columns became real cards to match the card-chassis themes above --
    same design system, different personality, rather than two
    unrelated looks in one picker."""
    margin = int(H * 0.045)
    _place_corner_flourishes(img, int(H * corner), gold, margin, rng)

    _card(img, _BLOOM["left"], card_fill, radius=26, border=card_border, shadow=False)
    _card(img, _BLOOM["right"], card_fill, radius=26, border=card_border, shadow=False)

    flowers = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    _draw_flower_medallion(flowers, W * 0.085, H * 0.135, H * 0.085,
                            petal_palette, center_color, leaf_color, rng)
    _draw_flower_medallion(flowers, W * 0.915, H * 0.885, H * 0.085,
                            petal_palette, center_color, leaf_color, rng)
    for _ in range(7):
        cx = rng.choice([rng.uniform(W * 0.30, W * 0.70), rng.uniform(W * 0.02, W * 0.10),
                         rng.uniform(W * 0.90, W * 0.98)])
        cy = rng.choice([rng.uniform(H * 0.02, H * 0.12), rng.uniform(H * 0.88, H * 0.98)])
        _draw_petal_flower(flowers, cx, cy, rng.uniform(H * 0.028, H * 0.05),
                            rng.choice(petal_palette), center_color, rng)
    img.alpha_composite(flowers)


def make_cherry_blossom(seed=5):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (255, 236, 242), (250, 212, 226)).convert("RGBA")
    _bloom_chassis(img,
                   gold=(206, 138, 106),
                   card_fill=(255, 250, 252, 172),
                   card_border=(226, 150, 175, 190),
                   petal_palette=[(246, 122, 162), (250, 168, 194), (238, 96, 142)],
                   center_color=(255, 238, 214),
                   leaf_color=(150, 196, 150),
                   rng=rng)
    return img.convert("RGB")


def make_lavender_bloom(seed=6):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (240, 233, 254), (214, 234, 244)).convert("RGBA")
    _bloom_chassis(img,
                   gold=(140, 120, 188),
                   card_fill=(253, 251, 255, 176),
                   card_border=(178, 160, 226, 190),
                   petal_palette=[(164, 130, 226), (146, 196, 226), (186, 158, 240)],
                   center_color=(246, 250, 238),
                   leaf_color=(146, 190, 172),
                   rng=rng)
    return img.convert("RGB")



# =====================================================================
# 7/8/9. The "flagship" backgrounds -- Fusion Core, Neon Pulse, Crimson
# Strike. These are a different kind of background from everything
# above: not a picture the layout happens to sit on, but the *chassis*
# of the layout itself -- the cards each stat block lives in, the
# dividers between them, the plot wells the history graphs draw into,
# the accent edges. Every rectangle here is positioned from the same
# fraction-of-panel constants the matching preset's elements use
# (_FUSION/_NEON/_CRIMSON below mirror dashboard_theme.py's preset
# entries), so a card and the gauge inside it can't drift apart.
#
# They also ship with `"dim": 0` (see _build_background_image()):
# everything here is drawn at the contrast it should actually appear
# at, rather than being a bright photo that needs knocking back 45%
# before text is legible over it.
# =====================================================================

# ---- shared drawing helpers for the card-style backgrounds ----------

def _px(box):
    """A (x0, y0, x1, y1) box in fractions of the panel -> pixels on
    this 1920x960 canvas. Every card/slab position in this section is
    written as fractions so it lines up with the preset elements, which
    are also fractions (dashboard_theme.py resolves those against the
    real panel size, whatever it is)."""
    return [box[0] * W, box[1] * H, box[2] * W, box[3] * H]


def _card(img, box, fill, radius=22, border=None, border_width=2, accent_edge=None,
          accent_width=8, shadow=True):
    """One rounded panel: an optional soft drop shadow, a translucent
    fill, an optional hairline border, and an optional thicker accent
    stripe down its left edge (the CPU/GPU color-coding the reference
    dashboards use to tell two identical-looking cards apart at a
    glance). Composited through an RGBA layer so `fill` can carry real
    alpha and let the background art show through the card."""
    x0, y0, x1, y1 = _px(box)
    if shadow:
        shadow_layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        rounded_rect(ImageDraw.Draw(shadow_layer), [x0 + 3, y0 + 6, x1 + 3, y1 + 8],
                     radius=radius, fill=(0, 0, 0, 120))
        shadow_layer = shadow_layer.filter(ImageFilter.GaussianBlur(14))
        img.alpha_composite(shadow_layer)
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    rounded_rect(draw, [x0, y0, x1, y1], radius=radius, fill=fill)
    if border:
        rounded_rect(draw, [x0, y0, x1, y1], radius=radius, outline=border, width=border_width)
    if accent_edge:
        # Clipped to the card's own rounded silhouette: draw the stripe
        # as a full rounded rect of accent color, then keep only the
        # left `accent_width` pixels of it via a mask, so the stripe
        # picks up the card's corner radius instead of sticking out
        # past it as a square-cornered bar.
        stripe = Image.new("RGBA", (W, H), (0, 0, 0, 0))
        rounded_rect(ImageDraw.Draw(stripe), [x0, y0, x1, y1], radius=radius, fill=accent_edge)
        mask = Image.new("L", (W, H), 0)
        ImageDraw.Draw(mask).rectangle([x0, y0, x0 + accent_width, y1], fill=255)
        stripe.putalpha(Image.composite(stripe.split()[3], Image.new("L", (W, H), 0), mask))
        layer.alpha_composite(stripe)
    img.alpha_composite(layer)


def _well(img, box, fill=(0, 0, 0, 90), radius=10, outline=None):
    """A recessed inner panel -- the darker plot area a history graph's
    line is drawn into, or the track a row of readings sits on. Same
    fraction-box convention as _card()."""
    x0, y0, x1, y1 = _px(box)
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    rounded_rect(ImageDraw.Draw(layer), [x0, y0, x1, y1], radius=radius, fill=fill, outline=outline)
    img.alpha_composite(layer)


def _ribbon(img, stops, y_center=0.5, thickness=0.42, wave=0.16, freq=1.25, phase=0.0,
            blur=90, alpha=255, angle_drop=0.34):
    """The wide diagonal color ribbon sweeping under the cards -- a
    multi-stop horizontal gradient shown through a soft-edged wavy band
    mask. Built as gradient-plus-mask rather than by drawing colored
    shapes directly so the color transition stays perfectly smooth
    across the whole sweep no matter how the band bends.

    `stops` are the gradient colors left-to-right; `y_center`/
    `angle_drop` set where the band starts vertically and how far it
    falls across the width (its diagonal), `thickness` how tall it is,
    `wave`/`freq`/`phase` the sine wobble along it, and `blur` how soft
    its edges are."""
    grad = Image.new("RGB", (W, H))
    gdraw = ImageDraw.Draw(grad)
    n = len(stops)
    for x in range(W):
        t = x / max(1, W - 1) * (n - 1)
        i = min(n - 2, int(t))
        f = t - i
        c = tuple(int(stops[i][k] * (1 - f) + stops[i + 1][k] * f) for k in range(3))
        gdraw.line([(x, 0), (x, H)], fill=c)

    mask = Image.new("L", (W, H), 0)
    mdraw = ImageDraw.Draw(mask)
    half = thickness * H / 2
    for x in range(0, W, 3):
        t = x / max(1, W - 1)
        cy = (y_center + (t - 0.5) * angle_drop) * H + math.sin(t * math.tau * freq + phase) * wave * H
        mdraw.line([(x, cy - half), (x, cy + half)], fill=alpha, width=4)
    mask = mask.filter(ImageFilter.GaussianBlur(blur))
    grad.putalpha(mask)
    img.alpha_composite(grad)


def _halftone(img, box, color, dot=7, gap=20, alpha=90, fade=True):
    """A dot-screen fill inside `box` (fractions) -- the comic/print
    halftone texture the bolder reference themes use behind their
    headline slabs. `fade` ramps the dots out toward the right so the
    texture dissolves instead of ending on a hard edge."""
    x0, y0, x1, y1 = _px(box)
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    y = y0
    row = 0
    while y < y1:
        x = x0 + (gap / 2 if row % 2 else 0)
        while x < x1:
            a = alpha
            if fade:
                a = int(alpha * max(0.0, 1.0 - (x - x0) / max(1.0, x1 - x0)))
            if a > 0:
                draw.ellipse([x, y, x + dot, y + dot], fill=(*color, a))
            x += gap
        y += gap
        row += 1
    img.alpha_composite(layer)


def _slab(img, points, fill, outline=None, width=4):
    """An angular polygon slab (fraction coordinates) -- the sharp
    diagonal shapes the cyber/comic themes are built out of."""
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    pts = [(x * W, y * H) for x, y in points]
    draw.polygon(pts, fill=fill)
    if outline:
        for i in range(len(pts)):
            draw.line([pts[i], pts[(i + 1) % len(pts)]], fill=outline, width=width)
    img.alpha_composite(layer)


def _glitch_bars(img, box, colors, rng, count=26, alpha=150):
    """Thin offset horizontal slivers in `box` -- cheap, convincing
    digital-glitch texture, and the only "noise" in these designs that
    is actually random rather than placed."""
    x0, y0, x1, y1 = _px(box)
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    for _ in range(count):
        y = rng.uniform(y0, y1)
        h = rng.uniform(2, 9)
        w = rng.uniform((x1 - x0) * 0.08, (x1 - x0) * 0.55)
        x = rng.uniform(x0, x1 - w)
        draw.rectangle([x, y, x + w, y + h], fill=(*rng.choice(colors), alpha))
    img.alpha_composite(layer)


# ---------------------------------------------------------------------
# 7. Fusion Core -- the dark card dashboard: a vivid color ribbon
# sweeping behind matte panels, one per component group, each with its
# own accent edge and graph well. Modeled on the modern all-in-one PC
# monitor layouts the user pointed at, built entirely from the helpers
# above.
# ---------------------------------------------------------------------
_FUSION = {
    "clock": (0.030, 0.065, 0.470, 0.300),
    "gpu": (0.030, 0.340, 0.470, 0.935),
    "cpu": (0.530, 0.065, 0.970, 0.600),
    "mem": (0.530, 0.640, 0.970, 0.935),
    "gpu_well": (0.055, 0.815, 0.445, 0.905),
    "cpu_well": (0.555, 0.478, 0.945, 0.568),
}


def make_fusion_core(seed=7):
    rng = random.Random(seed)
    img = vertical_gradient(W, H, (14, 16, 24), (7, 8, 13)).convert("RGBA")

    # The signature sweep: teal -> violet -> magenta -> amber, bent
    # through the panel. Three passes, widest and dimmest first: a huge
    # soft wash that tints the whole field (it reads through the cards'
    # near-opaque fill just enough to keep them from looking like grey
    # boxes cut out of a dark sheet), then the ribbon proper, then a
    # tight bright core along its spine. The first version had only the
    # middle two and the cards swallowed nearly all of it -- the sweep
    # only showed in the gutter between columns, so the composition
    # read as "dark panels" rather than "panels floating on light".
    _ribbon(img, [(0, 170, 190), (80, 70, 220), (215, 60, 170), (255, 140, 50)],
            y_center=0.50, thickness=1.15, wave=0.05, freq=0.9, blur=190, alpha=150)
    _ribbon(img, [(0, 200, 210), (110, 95, 240), (235, 75, 185), (255, 160, 65)],
            y_center=0.52, thickness=0.42, wave=0.13, freq=1.1, blur=110, alpha=235)
    _ribbon(img, [(120, 245, 250), (170, 130, 255), (255, 110, 210), (255, 200, 110)],
            y_center=0.54, thickness=0.14, wave=0.12, freq=1.1, blur=40, alpha=225)

    card_fill = (16, 18, 26, 232)
    border = (64, 70, 94, 255)
    _card(img, _FUSION["clock"], card_fill, border=border)
    _card(img, _FUSION["gpu"], card_fill, border=border, accent_edge=(236, 72, 153, 255))
    _card(img, _FUSION["cpu"], card_fill, border=border, accent_edge=(34, 211, 238, 255))
    _card(img, _FUSION["mem"], card_fill, border=border, accent_edge=(168, 85, 247, 255))
    _well(img, _FUSION["gpu_well"], fill=(0, 0, 0, 110))
    _well(img, _FUSION["cpu_well"], fill=(0, 0, 0, 110))
    return img.convert("RGB")


# ---------------------------------------------------------------------
# 8. Neon Pulse -- the loud one: an acid-yellow field cut by a magenta
# diagonal, glitch slivers, halftone, and two dark readout slabs for
# the CPU/GPU columns. Original shapes only -- the reference for this
# look was a piece of licensed key art, so what's borrowed is the
# palette and the angular energy, not the artwork.
# ---------------------------------------------------------------------
# The composition every one of the reference themes uses: a bold
# graphic zone down the left ~30% (where their key art / character
# sits) and the actual readout in panels filling the right. Shared by
# Neon Pulse and Crimson Strike below, which differ in palette and
# shape language, not structure -- and mirrored in those presets'
# element positions.
_SPLIT = {
    "art": (0.0, 0.0, 0.300, 1.0),
    "left_panel": [(0.335, 0.215), (0.645, 0.185), (0.645, 0.945), (0.335, 0.945)],
    "right_panel": [(0.665, 0.185), (0.975, 0.215), (0.975, 0.945), (0.665, 0.945)],
}


def _keyline(img, panel, color, thickness=0.016):
    """A bright bar along a panel's (skewed) top edge -- what stops the
    dark readout panels from reading as plain holes punched in the
    artwork."""
    a, b = panel[0], panel[1]
    _slab(img, [a, b, (b[0], b[1] + thickness), (a[0], a[1] + thickness)], (*color, 255))


def _chevrons(img, box, color, count=3, alpha=60, thickness=0.055):
    """Stacked right-pointing chevrons filling `box` -- the directional
    texture the bolder themes use in their art zone, standing in for
    the reference art's motion lines."""
    x0, y0, x1, y1 = box
    step = (y1 - y0) / (count + 1)
    for i in range(count):
        cy = y0 + step * (i + 1)
        _slab(img, [(x0, cy - thickness), (x1 * 0.62, cy + step * 0.42),
                    (x0, cy + step * 0.84 + thickness), (x0, cy + step * 0.84),
                    (x1 * 0.62 - thickness * 0.9, cy + step * 0.42), (x0, cy)],
              (*color, alpha))


def make_neon_pulse(seed=8):
    rng = random.Random(seed)
    yellow = (250, 232, 26)
    magenta = (236, 22, 110)
    cyan = (34, 226, 236)
    ink = (12, 12, 16)
    img = Image.new("RGBA", (W, H), (*magenta, 255))

    # Acid-yellow art block down the left, cut on a diagonal, with a
    # cyan keyline along the cut and ink halftone + chevrons filling it.
    _slab(img, [(0.0, 0.0), (0.300, 0.0), (0.245, 1.0), (0.0, 1.0)], (*yellow, 255))
    _slab(img, [(0.300, 0.0), (0.316, 0.0), (0.261, 1.0), (0.245, 1.0)], (*cyan, 255))
    _chevrons(img, (0.02, 0.42, 0.30, 0.98), ink, count=3, alpha=45)
    _halftone(img, (0.0, 0.0, 0.30, 1.0), ink, dot=9, gap=26, alpha=110)
    # Glitch slivers only in the magenta field's top/bottom margins, so
    # they never run across the readout panels and muddy the numbers.
    _glitch_bars(img, (0.33, 0.0, 1.0, 0.085), [yellow, cyan, (255, 255, 255)], rng, count=12, alpha=140)
    _glitch_bars(img, (0.33, 0.955, 1.0, 1.0), [yellow, cyan], rng, count=6, alpha=140)

    for panel, key in ((_SPLIT["left_panel"], cyan), (_SPLIT["right_panel"], yellow)):
        _slab(img, panel, (*ink, 236))
        _keyline(img, panel, key)
    return img.convert("RGB")


# ---------------------------------------------------------------------
# 9. Crimson Strike -- red/black/white, hard diagonals, halftone and a
# torn white slash: the high-contrast comic look, again as original
# geometry rather than anything traced from the reference art.
# ---------------------------------------------------------------------
def make_crimson_strike(seed=9):
    rng = random.Random(seed)
    red = (206, 20, 34)
    ink = (13, 11, 14)
    bone = (246, 244, 240)
    img = Image.new("RGBA", (W, H), (*red, 255))

    # Same left-art / right-readout split as Neon Pulse, in the
    # red-black-white comic register: an ink block down the left with a
    # torn white slash across it, red halftone bleeding right, and a
    # second slash cutting the top of the red field.
    _slab(img, [(0.0, 0.0), (0.300, 0.0), (0.245, 1.0), (0.0, 1.0)], (*ink, 255))
    _slab(img, [(0.0, 0.245), (0.300, 0.075), (0.300, 0.175), (0.0, 0.345)], (*bone, 255))
    _slab(img, [(0.0, 0.365), (0.300, 0.195), (0.300, 0.225), (0.0, 0.395)], (*red, 255))
    _chevrons(img, (0.015, 0.50, 0.29, 0.98), bone, count=3, alpha=42)
    _halftone(img, (0.30, 0.0, 0.62, 1.0), ink, dot=8, gap=24, alpha=85)
    # A hard ink wedge biting into the red from the top-right corner
    # keeps the right half from being a flat red rectangle behind the
    # panels.
    _slab(img, [(1.0, 0.0), (1.0, 0.30), (0.70, 0.0)], (*ink, 255))
    _slab(img, [(0.96, 0.0), (1.0, 0.0), (1.0, 0.06), (0.86, 0.0)], (*bone, 255))

    for panel in (_SPLIT["left_panel"], _SPLIT["right_panel"]):
        _slab(img, panel, (22, 19, 23, 240), outline=(*bone, 255), width=4)
    return img.convert("RGB")


if __name__ == "__main__":
    save(make_aurora(), "aurora.jpg")
    save(make_nebula(), "nebula.jpg")
    save(make_synthwave(), "synthwave.jpg")
    save(make_bokeh(), "bokeh.jpg")
    save(make_cherry_blossom(), "cherry_blossom.jpg")
    save(make_lavender_bloom(), "lavender_bloom.jpg")
    save(make_fusion_core(), "fusion_core.jpg")
    save(make_neon_pulse(), "neon_pulse.jpg")
    save(make_crimson_strike(), "crimson_strike.jpg")
